name: Pipe

on:
  push:
  pull_request:
    branches:
      - 'master'

jobs:
  regression-test:
    runs-on: ubuntu-latest

    container:
      image: cypress/included

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t cypress-test .    

      - name: Run Cypress Tests
        run: |
          docker run cypress-test
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
          
      - name: Deploy to GitHub Pages
        if: always()
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: gh-pages
          build_dir: ./cypress/reports/html
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}