name: Pipe

on:
  push:
  pull_request:
    branches:
      - 'master'

jobs:
  regression-test:
    runs-on: ubuntu-latest
    steps:
      - name: Project checkout
        uses: actions/checkout@v4

      - name: Installing dependencies
        run: npm install

      - name: EsLint verify
        run: npm run lint  

      - name: Running the tests
        uses: cypress-io/github-action@v5
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
          build: npm run build
          start: npm run test:report
          
      - name: Adding reports to GitHub pages
        if: always()
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: gh-pages
          build_dir: ./cypress/reports/html
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}