name: Pipe

on:
  push:
  pull_request:
    branches:
      - 'master'

jobs:
  regression-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: EsLint verify
        run: npm run lint  

      - name: Runner tests
        uses: cypress-io/github-action@v5
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
          API_POK: ${{ secrets.API_POK }}
          build: npm run build
          start: npm run test:report
          
      - name: Report deploy to gitHub pages
        if: always()
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: gh-pages
          build_dir: ./cypress/reports/html
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}